server:
  port: 9988

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneytransfer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: aeesgs-app
    version: '@project.version@'
